# Limpieza de datos FEMSA

En este reporte se llevara acabo una limpieza de datos para el socio formador FEMSA de la empresa Spin OXXO. El proposito es elaborar la limpieza de la base de datos para poder hacer un analisis profundo en una base limpia.

### Exportación de datos
Primero se exportan los datos para tener nuestra base lista en python y poder iniciar con la limpieza.

In [189]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel("credito.xlsx")
df.head()

,folio,Empresa,RFC,Cliente,folio 1,Status,Estatus_Cobranza,Solicitud,Fecha_Deposito,Fecha_de_primer_pago,loan_name,Monto,Plazo,Tasa_con_impuesto,Tasa_sin_impuesto,Frecuencia,Cuota,Cuotas
0,PPS721703558,Spin Crédito,CLI000001XXX,CLIENTE 00001,PPS721703558,Liquidado,Liquidado,12/17/2024,12/17/2024,12/20/2024,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,200.84,6
1,PPS776127481,Spin Crédito,CLI000002XXX,CLIENTE 00002,PPS776127481,Liquidado,Liquidado,12/19/2024,12/19/2024,12/24/2024,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,201.85,6
2,SIM-ID00001-01,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-01,Liquidado,Liquidado,1/17/2025,1/17/2025,2/17/2025,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5956.11,6
3,SIM-ID00001-02,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-02,Liquidado,Liquidado,2/17/2025,2/17/2025,3/17/2025,Préstamo Personal Spinner no Late Fee,35000.0,6,86.99,74.99,Mensual,6948.79,6
4,SIM-ID00001-03,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-03,Liquidado,Liquidado,3/17/2025,3/17/2025,4/17/2025,Préstamo Personal Spinner no Late Fee,40000.0,6,86.99,74.99,Mensual,7941.48,6

### Paso 1:identificación de duplicados, nulos y tipos de datos

El primer paso para una base de datos limpia es la identifiicación de valores duplicados, nulos y tipos de datos. Este procedimiento nos sirve para poder observar que tanta limpieza va a necesitar nuestra base de datos, ya que con esto podemos identificar columnas o valores nulos los cuales no nos sirven para nuestro analisis.

In [190]:
print("La cantidad de filas totales en la base de datos es:",len(df))

La cantidad de filas totales en la base de datos es: 10009

In [191]:
print("Valores nulos por columna:")
print(df.isnull().sum())

Valores nulos por columna:
folio                   0
Empresa                 0
RFC                     0
Cliente                 0
folio 1                 0
Status                  0
Estatus_Cobranza        0
Solicitud               0
Fecha_Deposito          0
Fecha_de_primer_pago    0
loan_name               0
Monto                   0
Plazo                   0
Tasa_con_impuesto       0
Tasa_sin_impuesto       0
Frecuencia              0
Cuota                   0
Cuotas                  0
dtype: int64

In [192]:
print("Valores duplicados por columna:")
print(df.duplicated().sum())

Valores duplicados por columna:
0

In [193]:
print("Tipos de datos por columna:")
print(df.info())

Tipos de datos por columna:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10009 entries, 0 to 10008
Data columns (total 18 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   folio                 10009 non-null  object
 1   Empresa               10009 non-null  object
 2   RFC                   10009 non-null  object
 3   Cliente               10009 non-null  object
 4   folio 1               10009 non-null  object
 5   Status                10009 non-null  object
 6   Estatus_Cobranza      10009 non-null  object
 7   Solicitud             10009 non-null  object
 8   Fecha_Deposito        10009 non-null  object
 9   Fecha_de_primer_pago  10009 non-null  object
 10  loan_name             10009 non-null  object
 11  Monto                 10009 non-null  float64
 12  Plazo                 10009 non-null  int64
 13  Tasa_con_impuesto     10009 non-null  float64
 14  Tasa_sin_impuesto     10009 non-null  float64
 15  Frecuencia            10009 non-null  object
 16  Cuota                 10009 non-null  float64
 17  Cuotas                10009 non-null  int64
dtypes: float64(4), int64(2), object(12)
memory usage: 1.4+ MB
None

### Paso 2:Limpieza de base de datos
En esta sección, removemos todos los datos de las columnas que tengan datos faltantes o datos duplicados, el proposito de este paso es para tener un mejor analisis con datos de calidad, ya que si hay datos que faltan no se puede hacer un analisis completo por lo cual se eliminan y con esto podemos utilizar los datos que si puedan generar valor a nuestro analisis.

In [194]:
df1 = df.dropna(subset=["Estatus_Cobranza", "Solicitud", "Fecha_Deposito", "Fecha_de_primer_pago", "loan_name", "Monto", "Plazo", "Tasa_con_impuesto", "Tasa_sin_impuesto", "Frecuencia", "Cuota", "Cuotas"])
print("Base de datos sin valores nulos")
df

Base de datos sin valores nulos

,folio,Empresa,RFC,Cliente,folio 1,Status,Estatus_Cobranza,Solicitud,Fecha_Deposito,Fecha_de_primer_pago,loan_name,Monto,Plazo,Tasa_con_impuesto,Tasa_sin_impuesto,Frecuencia,Cuota,Cuotas
0,PPS721703558,Spin Crédito,CLI000001XXX,CLIENTE 00001,PPS721703558,Liquidado,Liquidado,12/17/2024,12/17/2024,12/20/2024,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,200.84,6
1,PPS776127481,Spin Crédito,CLI000002XXX,CLIENTE 00002,PPS776127481,Liquidado,Liquidado,12/19/2024,12/19/2024,12/24/2024,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,201.85,6
2,SIM-ID00001-01,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-01,Liquidado,Liquidado,1/17/2025,1/17/2025,2/17/2025,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5956.11,6
3,SIM-ID00001-02,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-02,Liquidado,Liquidado,2/17/2025,2/17/2025,3/17/2025,Préstamo Personal Spinner no Late Fee,35000.0,6,86.99,74.99,Mensual,6948.79,6
4,SIM-ID00001-03,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-03,Liquidado,Liquidado,3/17/2025,3/17/2025,4/17/2025,Préstamo Personal Spinner no Late Fee,40000.0,6,86.99,74.99,Mensual,7941.48,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10004,SIM-ID00002-01,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-01,Liquidado,Liquidado,1/19/2025,1/19/2025,2/19/2025,Préstamo Personal Spinner no Late Fee,70000.0,6,86.99,74.99,Mensual,11666.67,6
10005,SIM-ID00002-02,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-02,Liquidado,Liquidado,2/19/2025,2/19/2025,3/19/2025,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5000.00,6
10006,SIM-ID00002-03,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-03,Liquidado,Liquidado,3/19/2025,3/19/2025,4/19/2025,Préstamo Personal Spinner no Late Fee,195000.0,6,86.99,74.99,Mensual,32500.00,6
10007,SIM-ID00002-04,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-04,Liquidado,Liquidado,4/19/2025,4/19/2025,5/19/2025,Préstamo Personal Spinner no Late Fee,25000.0,6,86.99,74.99,Mensual,4166.67,6
10008,SIM-ID00002-05,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-05,Liquidado,Liquidado,5/19/2025,5/19/2025,6/19/2025,Préstamo Personal Spinner no Late Fee,60000.0,6,86.99,74.99,Mensual,10000.00,6

In [208]:
df2 = df1.drop_duplicates(subset=["Estatus_Cobranza", "Solicitud", "Fecha_Deposito", "Fecha_de_primer_pago", "loan_name", "Monto", "Plazo", "Tasa_con_impuesto", "Tasa_sin_impuesto", "Frecuencia", "Cuota", "Cuotas"])
print("Base de datos sin valores nulos y duplicados")
df2

Base de datos sin valores nulos y duplicados

,folio,Empresa,RFC,Cliente,folio 1,Status,Estatus_Cobranza,Solicitud,Fecha_Deposito,Fecha_de_primer_pago,loan_name,Monto,Plazo,Tasa_con_impuesto,Tasa_sin_impuesto,Frecuencia,Cuota,Cuotas
0,PPS721703558,Spin Crédito,CLI000001XXX,CLIENTE 00001,PPS721703558,Liquidado,Liquidado,12/17/2024,12/17/2024,12/20/2024,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,200.84,6
1,PPS776127481,Spin Crédito,CLI000002XXX,CLIENTE 00002,PPS776127481,Liquidado,Liquidado,12/19/2024,12/19/2024,12/24/2024,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,201.85,6
2,SIM-ID00001-01,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-01,Liquidado,Liquidado,1/17/2025,1/17/2025,2/17/2025,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5956.11,6
3,SIM-ID00001-02,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-02,Liquidado,Liquidado,2/17/2025,2/17/2025,3/17/2025,Préstamo Personal Spinner no Late Fee,35000.0,6,86.99,74.99,Mensual,6948.79,6
4,SIM-ID00001-03,Spin Crédito,CLI000001XXX,CLIENTE 00001,SIM-ID00001-03,Liquidado,Liquidado,3/17/2025,3/17/2025,4/17/2025,Préstamo Personal Spinner no Late Fee,40000.0,6,86.99,74.99,Mensual,7941.48,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10004,SIM-ID00002-01,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-01,Liquidado,Liquidado,1/19/2025,1/19/2025,2/19/2025,Préstamo Personal Spinner no Late Fee,70000.0,6,86.99,74.99,Mensual,11666.67,6
10005,SIM-ID00002-02,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-02,Liquidado,Liquidado,2/19/2025,2/19/2025,3/19/2025,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5000.00,6
10006,SIM-ID00002-03,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-03,Liquidado,Liquidado,3/19/2025,3/19/2025,4/19/2025,Préstamo Personal Spinner no Late Fee,195000.0,6,86.99,74.99,Mensual,32500.00,6
10007,SIM-ID00002-04,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-04,Liquidado,Liquidado,4/19/2025,4/19/2025,5/19/2025,Préstamo Personal Spinner no Late Fee,25000.0,6,86.99,74.99,Mensual,4166.67,6
10008,SIM-ID00002-05,Spin Crédito,CLI000002XXX,CLIENTE 00002,SIM-ID00002-05,Liquidado,Liquidado,5/19/2025,5/19/2025,6/19/2025,Préstamo Personal Spinner no Late Fee,60000.0,6,86.99,74.99,Mensual,10000.00,6

In [196]:
import pandas as pd
from itertools import combinations

def encontrar_pares_duplicados(df):
    pares = []
    for col1, col2 in combinations(df.columns, 2):
        if df[col1].equals(df[col2]):
            pares.append((col1, col2))
    return pares

pares_duplicados = encontrar_pares_duplicados(df)

for original, duplicada in pares_duplicados:
    print(f"Las columnas duplicadas son: {duplicada} y {original}")

Las columnas duplicadas son: folio 1 y folio
Las columnas duplicadas son: Estatus_Cobranza y Status
Las columnas duplicadas son: Fecha_Deposito y Solicitud
Las columnas duplicadas son: Cuotas y Plazo

Despues de identificar cuales son las columnas duplicadas, se eliminan de nuestra base de datos las que no nos proporcionan datos utiles para nuestro analisis.En este caso "folio 1 " y "Status" fueron las columnas que se removieron de la base de datos debido a que tienen la misma información y hacen que nuestra base este mas limpia y ma simplificada.

In [197]:
df3 = df2.drop(columns=["folio 1","Status"])
print("Base de datos sin valores nulos, duplicados y sin columnas duplicadas")
df3

Base de datos sin valores nulos, duplicados y sin columnas duplicadas

,folio,Empresa,RFC,Cliente,Estatus_Cobranza,Solicitud,Fecha_Deposito,Fecha_de_primer_pago,loan_name,Monto,Plazo,Tasa_con_impuesto,Tasa_sin_impuesto,Frecuencia,Cuota,Cuotas
0,PPS721703558,Spin Crédito,CLI000001XXX,CLIENTE 00001,Liquidado,12/17/2024,12/17/2024,12/20/2024,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,200.84,6
1,PPS776127481,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,12/19/2024,12/19/2024,12/24/2024,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,201.85,6
2,SIM-ID00001-01,Spin Crédito,CLI000001XXX,CLIENTE 00001,Liquidado,1/17/2025,1/17/2025,2/17/2025,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5956.11,6
3,SIM-ID00001-02,Spin Crédito,CLI000001XXX,CLIENTE 00001,Liquidado,2/17/2025,2/17/2025,3/17/2025,Préstamo Personal Spinner no Late Fee,35000.0,6,86.99,74.99,Mensual,6948.79,6
4,SIM-ID00001-03,Spin Crédito,CLI000001XXX,CLIENTE 00001,Liquidado,3/17/2025,3/17/2025,4/17/2025,Préstamo Personal Spinner no Late Fee,40000.0,6,86.99,74.99,Mensual,7941.48,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10004,SIM-ID00002-01,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,1/19/2025,1/19/2025,2/19/2025,Préstamo Personal Spinner no Late Fee,70000.0,6,86.99,74.99,Mensual,11666.67,6
10005,SIM-ID00002-02,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,2/19/2025,2/19/2025,3/19/2025,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5000.00,6
10006,SIM-ID00002-03,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,3/19/2025,3/19/2025,4/19/2025,Préstamo Personal Spinner no Late Fee,195000.0,6,86.99,74.99,Mensual,32500.00,6
10007,SIM-ID00002-04,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,4/19/2025,4/19/2025,5/19/2025,Préstamo Personal Spinner no Late Fee,25000.0,6,86.99,74.99,Mensual,4166.67,6
10008,SIM-ID00002-05,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,5/19/2025,5/19/2025,6/19/2025,Préstamo Personal Spinner no Late Fee,60000.0,6,86.99,74.99,Mensual,10000.00,6

### Paso 3:Normalización de texto y tipos de datos
En este paso tiene la función de hacer que todos los datos de la columna sean el mismo para que no haya diferencuas entre los tipos de datos y en emomento de hacer el analisis sea un proceso mas fluido.En este caso la base de datos ya tiene los datos por lo cual este paso no es necesario de realizar, solo por cuestiones de formato se remueven los espacios en blanco al inicio/final en columnas de texto. Tambien se muestran todos los titulos de las columnas con mayuscula.

In [198]:
columnas_texto = df3.select_dtypes(include="object").columns
for col in columnas_texto:
    df3[col] = df3[col].str.strip()

df3.columns = df3.columns.str.capitalize()
df3

,Folio,Empresa,Rfc,Cliente,Estatus_cobranza,Solicitud,Fecha_deposito,Fecha_de_primer_pago,Loan_name,Monto,Plazo,Tasa_con_impuesto,Tasa_sin_impuesto,Frecuencia,Cuota,Cuotas
0,PPS721703558,Spin Crédito,CLI000001XXX,CLIENTE 00001,Liquidado,12/17/2024,12/17/2024,12/20/2024,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,200.84,6
1,PPS776127481,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,12/19/2024,12/19/2024,12/24/2024,Préstamo Personal Spinner no Late Fee,1011.6,6,86.99,74.99,Mensual,201.85,6
2,SIM-ID00001-01,Spin Crédito,CLI000001XXX,CLIENTE 00001,Liquidado,1/17/2025,1/17/2025,2/17/2025,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5956.11,6
3,SIM-ID00001-02,Spin Crédito,CLI000001XXX,CLIENTE 00001,Liquidado,2/17/2025,2/17/2025,3/17/2025,Préstamo Personal Spinner no Late Fee,35000.0,6,86.99,74.99,Mensual,6948.79,6
4,SIM-ID00001-03,Spin Crédito,CLI000001XXX,CLIENTE 00001,Liquidado,3/17/2025,3/17/2025,4/17/2025,Préstamo Personal Spinner no Late Fee,40000.0,6,86.99,74.99,Mensual,7941.48,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10004,SIM-ID00002-01,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,1/19/2025,1/19/2025,2/19/2025,Préstamo Personal Spinner no Late Fee,70000.0,6,86.99,74.99,Mensual,11666.67,6
10005,SIM-ID00002-02,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,2/19/2025,2/19/2025,3/19/2025,Préstamo Personal Spinner no Late Fee,30000.0,6,86.99,74.99,Mensual,5000.00,6
10006,SIM-ID00002-03,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,3/19/2025,3/19/2025,4/19/2025,Préstamo Personal Spinner no Late Fee,195000.0,6,86.99,74.99,Mensual,32500.00,6
10007,SIM-ID00002-04,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,4/19/2025,4/19/2025,5/19/2025,Préstamo Personal Spinner no Late Fee,25000.0,6,86.99,74.99,Mensual,4166.67,6
10008,SIM-ID00002-05,Spin Crédito,CLI000002XXX,CLIENTE 00002,Liquidado,5/19/2025,5/19/2025,6/19/2025,Préstamo Personal Spinner no Late Fee,60000.0,6,86.99,74.99,Mensual,10000.00,6

### Paso 4:Variables calculadas
En esta sección se realizaran calculaciones de variables que podrian llegar a ser util para nuestro analisis, de esta forma la hacer el tablero ya tendremos una noción de la información que queremos visualizar.

In [202]:
Tipos_de_prestamo = df3["Loan_name"].value_counts()
Tipos_de_prestamo

Loan_name
Micro P 8N                                1135
Micro P 810                               1012
Préstamo Personal Spinner no Late Fee      856
Préstamo Personal Spinner Late Fee 50      665
Micro P 15N                                513
Micro P 1510                               495
Préstamo Personal Spinner Late Fee 100     177
Micro P 815                                164
Micro P 1515                                74
Name: count, dtype: int64

In [203]:
Plazos_diferentes = df3["Plazo"].value_counts()
Plazos_diferentes

Plazo
8     2373
4     1020
12     935
6      763
Name: count, dtype: int64

In [206]:
Monto_promedio = df3["Monto"].mean()
Monto_minimo = df3["Monto"].min()
Monto_maximo = df3["Monto"].max()
print("El monto promedio es:",Monto_promedio)
print("El monto mínimo es:",Monto_minimo)
print("El monto máximo es:",Monto_maximo)

El monto promedio es: 1829.2644549204479
El monto mínimo es: 327.84
El monto máximo es: 300000.0

In [213]:
df3.to_excel("Base_Operaciones_credito_limpio.xlsx", index=False)
print("Base de datos limpia guardada en Excel como Base_Operaciones_credito_limpio.xlsx")

Base de datos limpia guardada en Excel como Base_Operaciones_credito_limpio.xlsx